### ISSUE TITLE
module not found...

### ISSUE THREAD

**Issue by ShashaankHari** [XiaomiFirmwareUpdater/xiaomi-flashable-firmware-creator-gui#1]
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\lib\site-packages\xiaomi_flashable_firmware_creator_gui\__main__.py", line 3, in <module>
    from xiaomi_flashable_firmware_creator_gui.main import main
  File "C:\Program Files\Python39\lib\site-packages\xiaomi_flashable_firmware_creator_gui\main.py", line 17, in <module>
    from xiaomi_flashable_firmware_creator.firmware_creator import FlashableFirmwareCreator
  File "C:\Program Files\Python39\lib\site-packages\xiaomi_flashable_firmware_creator\firmware_creator.py", line 19, in <module>
    from xiaomi_flashable_firmware_creator.extractors.handlers.android_one_zip import AndroidOneZip
  File "C:\Program Files\Python39\lib\site-packages\xiaomi_flashable_firmware_creator\extractors\handlers\android_one_zip.py", line 4, in <module>
    from google.protobuf.pyext._message import RepeatedCompositeContainer
ModuleNotFoundError: No module named 'google.protobuf.pyext._message'

this is the error I get whenever i try to use the v2 gui
I tried uninstalling protobuf and reinstalling, problem still persists

**Comment by legitishan** [comment]
How did you install protobuf? Using pip?

**Comment by ShashaankHari** [comment]
> How did you install protobuf? Using pip?

yes..

**Comment by yshalsager** [comment]
There is an issue with python 3.9, for now please use a lower version

**Comment by ShashaankHari** [comment]
> There is an issue with python 3.9, for now please use a lower version

ohok

**Comment by yshalsager** [comment]
Fixed with https://github.com/XiaomiFirmwareUpdater/xiaomi-flashable-firmware-creator-gui/commit/96854b6c38aab0de34a7bacde3ce82e7c082c33b
Please update to v2.3.1 using pip or poetry.

**Comment by ShashaankHari** [comment]
> Fixed with [96854b6](https://github.com/XiaomiFirmwareUpdater/xiaomi-flashable-firmware-creator-gui/commit/96854b6c38aab0de34a7bacde3ce82e7c082c33b)
> Please update to v2.3.1 using pip or poetry.

I have updated to latest pip and latest version, on python 3.9

C:\Users\Arvind C>pip install xiaomi_flashable_firmware_creator_gui
Collecting xiaomi_flashable_firmware_creator_gui
  Downloading xiaomi_flashable_firmware_creator_gui-2.3.2-py3-none-any.whl (311 kB)
     |████████████████████████████████| 311 kB 224 kB/s
Collecting xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0
  Downloading xiaomi_flashable_firmware_creator-2.1.1-py3-none-any.whl (164 kB)
     |████████████████████████████████| 164 kB 102 kB/s
Requirement already satisfied: PyQt5<6.0.0,>=5.13.0 in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from xiaomi_flashable_firmware_creator_gui) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from PyQt5<6.0.0,>=5.13.0->xiaomi_flashable_firmware_creator_gui) (12.8.1)
Collecting protobuf<4.0.0,>=3.15.0
  Downloading protobuf-3.15.7-py2.py3-none-any.whl (173 kB)
     |████████████████████████████████| 173 kB 261 kB/s
Requirement already satisfied: remotezip<0.10.0,>=0.9.2 in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (0.9.2)
Requirement already satisfied: six>=1.9 in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from protobuf<4.0.0,>=3.15.0->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (1.15.0)
Requirement already satisfied: tabulate in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from remotezip<0.10.0,>=0.9.2->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (0.8.7)
Requirement already satisfied: requests in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from remotezip<0.10.0,>=0.9.2->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from requests->remotezip<0.10.0,>=0.9.2->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from requests->remotezip<0.10.0,>=0.9.2->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (1.26.3)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from requests->remotezip<0.10.0,>=0.9.2->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\users\arvind c\appdata\roaming\python\python39\site-packages (from requests->remotezip<0.10.0,>=0.9.2->xiaomi_flashable_firmware_creator<3.0.0,>=2.1.0->xiaomi_flashable_firmware_creator_gui) (2.10)
Installing collected packages: protobuf, xiaomi-flashable-firmware-creator, xiaomi-flashable-firmware-creator-gui
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.14.0
    Uninstalling protobuf-3.14.0:
      Successfully uninstalled protobuf-3.14.0
Successfully installed protobuf-3.15.7 xiaomi-flashable-firmware-creator-2.1.1 xiaomi-flashable-firmware-creator-gui-2.3.2

C:\Users\Arvind C>xiaomi_flashable_firmware_creator_g
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\xiaomi_flashable_firmware_creator_g.exe\__main__.py", line 4, in <module>
  File "c:\program files\python39\lib\site-packages\xiaomi_flashable_firmware_creator_gui\main.py", line 17, in <module>
    from xiaomi_flashable_firmware_creator.firmware_creator import FlashableFirmwareCreator
  File "c:\program files\python39\lib\site-packages\xiaomi_flashable_firmware_creator\firmware_creator.py", line 19, in <module>
    from xiaomi_flashable_firmware_creator.extractors.handlers.android_one_zip import AndroidOneZip
  File "c:\program files\python39\lib\site-packages\xiaomi_flashable_firmware_creator\extractors\handlers\android_one_zip.py", line 4, in <module>
    from google.protobuf.pyext._message import RepeatedCompositeContainer
ModuleNotFoundError: No module named 'google.protobuf.pyext._message'

Still same error..

**Comment by yshalsager** [comment]
@ShashaankHari Seems this problem still happens on Windows, even after updating Google's protobuf. Anyways, I have dropped `RepeatedCompositeContainer` import. This should fix the issue permanently. Please update the GUI package and try again.

**Comment by ShashaankHari** [comment]
> @ShashaankHari Seems this problem still happens on Windows, even after updating Google's protobuf. Anyways, I have dropped `RepeatedCompositeContainer` import. This should fix the issue permanently. Please update the GUI package and try again.

Indeed still not working why is google protobuf messing this up still the same error..  

xiaomi_flashable_firmware_creator_g
Traceback (most recent call last):
  File "c:\program files\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\xiaomi_flashable_firmware_creator_g.exe\__main__.py", line 4, in <module>
  File "c:\program files\python39\lib\site-packages\xiaomi_flashable_firmware_creator_gui\main.py", line 17, in <module>
    from xiaomi_flashable_firmware_creator.firmware_creator import FlashableFirmwareCreator
  File "c:\program files\python39\lib\site-packages\xiaomi_flashable_firmware_creator\firmware_creator.py", line 19, in <module>
    from xiaomi_flashable_firmware_creator.extractors.handlers.android_one_zip import AndroidOneZip
  File "c:\program files\python39\lib\site-packages\xiaomi_flashable_firmware_creator\extractors\handlers\android_one_zip.py", line 4, in <module>
    from google.protobuf.pyext._message import RepeatedCompositeContainer
ModuleNotFoundError: No module named 'google.protobuf.pyext._message'

**Comment by yshalsager** [comment]
@ShashaankHari no way.. please preform a clean installation on a separate virtual environment. That line of code in the error log doesn't exist now..

**Comment by ShashaankHari** [comment]
> @ShashaankHari no way.. please preform a clean installation on a separate virtual environment. That line of code in the error log doesn't exist now..

ok ill try
